################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
K_SRCS := 
LD_SRCS := 
S67_SRCS := 
LDS_SRCS := 
CMD_SRCS := 
EXE_SRCS := 
CXX_SRCS := 
CMD_UPPER_SRCS := 
ELF_SRCS := 
C43_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
C62_SRCS := 
S_UPPER_SRCS := 
A_SRCS := 
C55_SRCS := 
SA_SRCS := 
LDS_UPPER_SRCS := 
C_UPPER_SRCS := 
OUT_SRCS := 
OBJ_SRCS := 
S62_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S??_SRCS := 
C++_SRCS := 
CLA_SRCS := 
ASM_UPPER_SRCS := 
C_SRCS := 
C67_SRCS := 
S_SRCS := 
S43_SRCS := 
OPT_SRCS := 
C64_SRCS := 
C??_SRCS := 
CC_SRCS := 
S64_SRCS := 
OBJS := 
BIN_OUTPUTS := 
S_DEPS := 
S_UPPER_DEPS := 
S62_DEPS := 
C64_DEPS := 
ASM_DEPS := 
CC_DEPS := 
S55_DEPS := 
C67_DEPS := 
C??_DEPS := 
CLA_DEPS := 
CPP_DEPS := 
S??_DEPS := 
C_DEPS := 
C62_DEPS := 
EXE_OUTPUTS := 
CXX_DEPS := 
C++_DEPS := 
ASM_UPPER_DEPS := 
K_DEPS := 
C43_DEPS := 
S67_DEPS := 
SA_DEPS := 
S43_DEPS := 
OPT_DEPS := 
S64_DEPS := 
C_UPPER_DEPS := 
C55_DEPS := 
CPP_DEPS__QUOTED := 
C67_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
EXE_OUTPUTS__QUOTED := 
S67_DEPS__QUOTED := 
BIN_OUTPUTS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
K_DEPS__QUOTED := 
C64_DEPS__QUOTED := 
C++_DEPS__QUOTED := 
OBJS__QUOTED := 
S43_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
C55_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S64_DEPS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
firmware/openos/projects/common \
firmware/openos/projects/common/03oos_openwsn \
firmware/openos/openwsn \
firmware/openos/openwsn/cross-layers \
firmware/openos/openwsn/07-App/udpstorm \
firmware/openos/openwsn/07-App/udprand \
firmware/openos/openwsn/07-App/udpprint \
firmware/openos/openwsn/07-App/udplatency \
firmware/openos/openwsn/07-App/udpinject \
firmware/openos/openwsn/07-App/udpecho \
firmware/openos/openwsn/07-App/tcpprint \
firmware/openos/openwsn/07-App/tcpinject \
firmware/openos/openwsn/07-App/tcpecho \
firmware/openos/openwsn/07-App/rwellknown \
firmware/openos/openwsn/07-App/rrt \
firmware/openos/openwsn/07-App/rreg \
firmware/openos/openwsn/07-App/rleds \
firmware/openos/openwsn/07-App/rinfo \
firmware/openos/openwsn/07-App/rex \
firmware/openos/openwsn/07-App/r6t \
firmware/openos/openwsn/07-App/ohlone \
firmware/openos/openwsn/07-App/layerdebug \
firmware/openos/openwsn/04-TRAN \
firmware/openos/openwsn/03b-IPv6 \
firmware/openos/openwsn/03a-IPHC \
firmware/openos/openwsn/02b-MAChigh \
firmware/openos/openwsn/02a-MAClow \
firmware/openos/kernel/openos \
firmware/openos/drivers/common \
firmware/openos/bsp/boards/cc2538em \
firmware/openos/bsp/boards/cc2538em/source \
firmware/openos/bsp/boards/cc2538em/sens_itf \

