################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
K_SRCS := 
LD_SRCS := 
S67_SRCS := 
LDS_SRCS := 
CMD_SRCS := 
EXE_SRCS := 
CXX_SRCS := 
CMD_UPPER_SRCS := 
ELF_SRCS := 
C43_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
C62_SRCS := 
S_UPPER_SRCS := 
A_SRCS := 
C55_SRCS := 
SA_SRCS := 
LDS_UPPER_SRCS := 
C_UPPER_SRCS := 
OUT_SRCS := 
OBJ_SRCS := 
S62_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S??_SRCS := 
C++_SRCS := 
CLA_SRCS := 
ASM_UPPER_SRCS := 
C_SRCS := 
C67_SRCS := 
S_SRCS := 
S43_SRCS := 
OPT_SRCS := 
C64_SRCS := 
C??_SRCS := 
CC_SRCS := 
S64_SRCS := 
OBJS := 
BIN_OUTPUTS := 
S_DEPS := 
S_UPPER_DEPS := 
S62_DEPS := 
C64_DEPS := 
ASM_DEPS := 
CC_DEPS := 
S55_DEPS := 
C67_DEPS := 
C??_DEPS := 
CLA_DEPS := 
CPP_DEPS := 
S??_DEPS := 
C_DEPS := 
C62_DEPS := 
EXE_OUTPUTS := 
CXX_DEPS := 
C++_DEPS := 
ASM_UPPER_DEPS := 
K_DEPS := 
C43_DEPS := 
S67_DEPS := 
SA_DEPS := 
S43_DEPS := 
OPT_DEPS := 
S64_DEPS := 
C_UPPER_DEPS := 
C55_DEPS := 
CPP_DEPS__QUOTED := 
C67_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
EXE_OUTPUTS__QUOTED := 
S67_DEPS__QUOTED := 
BIN_OUTPUTS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
K_DEPS__QUOTED := 
C64_DEPS__QUOTED := 
C++_DEPS__QUOTED := 
OBJS__QUOTED := 
S43_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
C55_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S64_DEPS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
firmware/openos/projects/xpressohack/OpenWSN_OS/src \
firmware/openos/projects/xpressohack/OpenWSN_OS/src/OpenAL \
firmware/openos/projects/xpressohack/OpenWSN_OS/src/OpenAL/internal \
firmware/openos/projects/xpressohack/01bsp_timers/application \
firmware/openos/projects/xpressohack/01bsp_spi/application \
firmware/openos/projects/xpressohack/01bsp_radio/application \
firmware/openos/projects/xpressohack/01bsp_leds/application \
firmware/openos/projects/xpressohack/00std_spi/src \
firmware/openos/projects/xpressohack/00std_eui64b/src \
firmware/openos/projects/wsn430v14/00std_uart \
firmware/openos/projects/wsn430v14/00std_spi \
firmware/openos/projects/wsn430v14/00std_leds_xtal \
firmware/openos/projects/wsn430v14/00std_i2c \
firmware/openos/projects/wsn430v14/00std_eui64 \
firmware/openos/projects/wsn430v14/00std_clocks \
firmware/openos/projects/wsn430v14/00std_button \
firmware/openos/projects/wsn430v13b/00std_uart \
firmware/openos/projects/wsn430v13b/00std_spi \
firmware/openos/projects/wsn430v13b/00std_leds_xtal \
firmware/openos/projects/wsn430v13b/00std_i2c \
firmware/openos/projects/wsn430v13b/00std_eui64 \
firmware/openos/projects/wsn430v13b/00std_clocks \
firmware/openos/projects/wsn430v13b/00std_button \
firmware/openos/projects/telosb/00std_uart \
firmware/openos/projects/telosb/00std_spi \
firmware/openos/projects/telosb/00std_leds_xtal \
firmware/openos/projects/telosb/00std_i2c \
firmware/openos/projects/telosb/00std_eui64 \
firmware/openos/projects/telosb/00std_clocks \
firmware/openos/projects/telosb/00std_button \
firmware/openos/projects/openmotestm/01bsp_flash/application \
firmware/openos/projects/openmotestm/00std_low_power_mode \
firmware/openos/projects/gina/old \
firmware/openos/projects/gina/02drv_headsup \
firmware/openos/projects/gina/00std_uart \
firmware/openos/projects/gina/00std_timers \
firmware/openos/projects/gina/00std_leds_xtal \
firmware/openos/projects/gina/00std_eui64 \
firmware/openos/projects/common \
firmware/openos/projects/common/03oos_openwsn \
firmware/openos/projects/common/03oos_macpong \
firmware/openos/projects/common/02drv_opentimers \
firmware/openos/projects/common/02drv_openserial \
firmware/openos/projects/common/01bsp_uart \
firmware/openos/projects/common/01bsp_spi \
firmware/openos/projects/common/01bsp_radiotimer \
firmware/openos/projects/common/01bsp_radio_tx \
firmware/openos/projects/common/01bsp_radio_rx \
firmware/openos/projects/common/01bsp_radio \
firmware/openos/projects/common/01bsp_leds \
firmware/openos/projects/common/01bsp_debugpins \
firmware/openos/projects/common/01bsp_closetimers \
firmware/openos/projects/common/01bsp_bsp_timer \
firmware/openos/projects/common/01bsp_bothtimers \
firmware/openos/projects/agilefox/01bsp_flash/application \
firmware/openos/projects/agilefox/00std_low_power_mode \
firmware/openos/openwsn \
firmware/openos/openwsn/cross-layers \
firmware/openos/openwsn/07-App/udpstorm \
firmware/openos/openwsn/07-App/udprand \
firmware/openos/openwsn/07-App/udpprint \
firmware/openos/openwsn/07-App/udplatency \
firmware/openos/openwsn/07-App/udpinject \
firmware/openos/openwsn/07-App/udpecho \
firmware/openos/openwsn/07-App/tcpprint \
firmware/openos/openwsn/07-App/tcpinject \
firmware/openos/openwsn/07-App/tcpecho \
firmware/openos/openwsn/07-App/swarmband \
firmware/openos/openwsn/07-App/rxl1 \
firmware/openos/openwsn/07-App/rwellknown \
firmware/openos/openwsn/07-App/rt \
firmware/openos/openwsn/07-App/rrube \
firmware/openos/openwsn/07-App/rrt \
firmware/openos/openwsn/07-App/rreg \
firmware/openos/openwsn/07-App/rleds \
firmware/openos/openwsn/07-App/rinfo \
firmware/openos/openwsn/07-App/rheli \
firmware/openos/openwsn/07-App/rex \
firmware/openos/openwsn/07-App/r6t \
firmware/openos/openwsn/07-App/ohlone \
firmware/openos/openwsn/07-App/layerdebug \
firmware/openos/openwsn/07-App/imu \
firmware/openos/openwsn/07-App/heli \
firmware/openos/openwsn/04-TRAN \
firmware/openos/openwsn/03b-IPv6 \
firmware/openos/openwsn/03a-IPHC \
firmware/openos/openwsn/02b-MAChigh \
firmware/openos/openwsn/02a-MAClow \
firmware/openos/openwsn/02a-MAClow/stupidmac \
firmware/openos/openwsn/02.5-MPLS \
firmware/openos/kernel/openos \
firmware/openos/kernel/FreeRTOS/FreeRTOS_MPU_Library \
firmware/openos/kernel/FreeRTOS/FreeRTOS_MPU_Library/portable \
firmware/openos/kernel/FreeRTOS/FreeRTOS_MPU_Library/demo_code \
firmware/openos/kernel/FreeRTOS/FreeRTOS_Library \
firmware/openos/kernel/FreeRTOS/FreeRTOS_Library/portable \
firmware/openos/kernel/FreeRTOS/FreeRTOS_Library/demo_code \
firmware/openos/kernel/FreeRTOS/CMSISv2p00_LPC17xx/src \
firmware/openos/drivers/z1 \
firmware/openos/drivers/gina \
firmware/openos/drivers/common \
firmware/openos/bsp/chips/cc2420 \
firmware/openos/bsp/chips/cc1101 \
firmware/openos/bsp/chips/at86rf231 \
firmware/openos/bsp/boards/z1 \
firmware/openos/bsp/boards/xpressohack \
firmware/openos/bsp/boards/wsn430v14 \
firmware/openos/bsp/boards/wsn430v13b \
firmware/openos/bsp/boards/telosb \
firmware/openos/bsp/boards/python \
firmware/openos/bsp/boards/openmotestm \
firmware/openos/bsp/boards/openmotestm/library/src \
firmware/openos/bsp/boards/openmotestm/ewarm \
firmware/openos/bsp/boards/openmotestm/configure \
firmware/openos/bsp/boards/k20/cpu \
firmware/openos/bsp/boards/k20/common \
firmware/openos/bsp/boards/k20/bsp_ext \
firmware/openos/bsp/boards/k20/bsp \
firmware/openos/bsp/boards/iot-lab_M3 \
firmware/openos/bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/STM32F10x_StdPeriph_Driver/src \
firmware/openos/bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x \
firmware/openos/bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/iar \
firmware/openos/bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/gcc_ride7 \
firmware/openos/bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/arm \
firmware/openos/bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/TrueSTUDIO \
firmware/openos/bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/CoreSupport \
firmware/openos/bsp/boards/iot-lab_M3/configure \
firmware/openos/bsp/boards/gina \
firmware/openos/bsp/boards/ez430-rf2500 \
firmware/openos/bsp/boards/eldorado \
firmware/openos/bsp/boards/derfmega \
firmware/openos/bsp/boards/common \
firmware/openos/bsp/boards/cc2538em \
firmware/openos/bsp/boards/cc2538em/source \
firmware/openos/bsp/boards/cc2538 \
firmware/openos/bsp/boards/cc2538/source \
firmware/openos/bsp/boards/agilefox \
firmware/openos/bsp/boards/agilefox/library/src \
firmware/openos/bsp/boards/agilefox/ewarm \
firmware/openos/bsp/boards/agilefox/configure \
firmware/openos/bootloader/k20 \
firmware/openos/bootloader/k20/usb \
firmware/openos/bootloader/k20/startup \
firmware/openos/bootloader/k20/disk_flash_utils \
firmware/openos/bootloader/k20/bootloader \

